CITIES = [
    "Москва", "Санкт-Петербург", "Новосибирск", "Екатеринбург", "Казань",
    "Нижний Новгород", "Челябинск", "Самара", "Уфа", "Ростов-на-Дону",
    "Омск", "Краснодар", "Воронеж", "Пермь", "Волгоград",
    "Красноярск", "Саратов", "Тюмень", "Тольятти", "Ижевск",
    "Барнаул", "Хабаровск", "Иркутск", "Владивосток", "Ярославль",
    "Махачкала", "Томск", "Оренбург", "Кемерово", "Новокузнецк",
]

SPECIALISTS = [
    {
        "id": "plumber_1",
        "type": "🔞Интим",
        "name": "Анна",
        "age": 21,
        "weight": 52,
        "height": 165,
        "bust": 92,
        "waist": 62,
        "hips": 94,
        "price": 4500,
        "photo": "Photos/1.png",
    },
    {
        "id": "plumber_2",
        "type": "🔞Интим",
        "name": "Инна",
        "age": 18,
        "weight": 50,
        "height": 162,
        "bust": 90,
        "waist": 60,
        "hips": 92,
        "price": 5000,
        "photo": "Photos/2.png",
    },
    {
        "id": "plumber_3",
        "type": "🔞Интим",
        "name": "Саша",
        "age": 20,
        "weight": 53,
        "height": 166,
        "bust": 93,
        "waist": 63,
        "hips": 95,
        "price": 4700,
        "photo": "Photos/3.png",
    },
    {
        "id": "plumber_4",
        "type": "🔞Интим",
        "name": "Алена",
        "age": 19,
        "weight": 51,
        "height": 163,
        "bust": 91,
        "waist": 61,
        "hips": 93,
        "price": 4200,
        "photo": "Photos/4.png",
    },
    {
        "id": "plumber_5",
        "type": "🔞Интим",
        "name": "Женя",
        "age": 21,
        "weight": 54,
        "height": 167,
        "bust": 94,
        "waist": 64,
        "hips": 96,
        "price": 4450,
        "photo": "Photos/5.png",
    },
    {
        "id": "plumber_6",
        "type": "🔞Интим",
        "name": "Настя",
        "age": 19,
        "weight": 52,
        "height": 164,
        "bust": 92,
        "waist": 62,
        "hips": 94,
        "price": 4300,
        "photo": "Photos/6.png",
    },
    {
        "id": "plumber_7",
        "type": "🔞Интим",
        "name": "Маша",
        "age": 21,
        "weight": 50,
        "height": 160,
        "bust": 90,
        "waist": 60,
        "hips": 91,
        "price": 4000,
        "photo": "Photos/7.png",
    },
    {
        "id": "plumber_8",
        "type": "🔞Интим",
        "name": "Соня",
        "age": 22,
        "weight": 55,
        "height": 168,
        "bust": 95,
        "waist": 65,
        "hips": 97,
        "price": 3700,
        "photo": "Photos/8.png",
    },
    {
        "id": "carpenter_1",
        "type": "☺️ Просто отдых",
        "name": "Лена",
        "age": 22,
        "weight": 52,
        "height": 164,
        "bust": 91,
        "waist": 61,
        "hips": 93,
        "price": 3200,
        "photo": "Photos/9.png",
    },
    {
        "id": "carpenter_2",
        "type": "☺️ Просто отдых",
        "name": "Ира",
        "age": 18,
        "weight": 50,
        "height": 161,
        "bust": 90,
        "waist": 60,
        "hips": 91,
        "price": 3400,
        "photo": "Photos/10.png",
    },
    {
        "id": "carpenter_3",
        "type": "☺️ Просто отдых",
        "name": "Оля",
        "age": 18,
        "weight": 51,
        "height": 162,
        "bust": 90,
        "waist": 61,
        "hips": 92,
        "price": 3200,
        "photo": "Photos/11.png",
    },
    {
        "id": "carpenter_4",
        "type": "☺️ Просто отдых",
        "name": "Вика",
        "age": 21,
        "weight": 53,
        "height": 165,
        "bust": 92,
        "waist": 62,
        "hips": 94,
        "price": 3000,
        "photo": "Photos/12.png",
    },
    {
        "id": "carpenter_5",
        "type": "☺️ Просто отдых",
        "name": "Настя",
        "age": 18,
        "weight": 50,
        "height": 160,
        "bust": 90,
        "waist": 60,
        "hips": 91,
        "price": 3300,
        "photo": "Photos/13.png",
    },
    {
        "id": "carpenter_6",
        "type": "☺️ Просто отдых",
        "name": "Маша",
        "age": 19,
        "weight": 52,
        "height": 163,
        "bust": 91,
        "waist": 61,
        "hips": 93,
        "price": 3200,
        "photo": "Photos/14.png",
    },
    {
        "id": "carpenter_7",
        "type": "☺️ Просто отдых",
        "name": "Каролина",
        "age": 18,
        "weight": 54,
        "height": 167,
        "bust": 94,
        "waist": 63,
        "hips": 96,
        "price": 3500,
        "photo": "Photos/15.png",
    },
    {
        "id": "carpenter_8",
        "type": "☺️ Просто отдых",
        "name": "Лина",
        "age": 19,
        "weight": 53,
        "height": 166,
        "bust": 93,
        "waist": 62,
        "hips": 95,
        "price": 3800,
        "photo": "Photos/16.png",
    },
]

PAYMENT_DETAILS = {
    "bank": "Сбербанк",
    "card": "4276 1234 5678 9012",
    "name": "Иван И.",
    "phone": "+7 (900) 123-45-67",
}
